[package]
name = "hells-gate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
memoffset = "0.9.0"
#windows-sys = { version = "0.52.0" , features = ["Win32_Foundation", "Win32_System_Kernel"]}
